### ISSUE TITLE
Timer question

### ISSUE THREAD

**Issue by kodarn** [Sineos/node-red-contrib-timeouttrigger#1]
Hello!

I have a question regarding timeouttrigger node.

Lets say that I have a flow running containing some timeouttrigger nodes running in waiting state. What happends to those running timers if I hit the red Deploy-button in Node-Red (when the flow is running)? Will those active flow(s) be terminated and thus killing our timeouttrigger nodes, or will they continue?

The reason for me asking is to determine if I should be developing on a production system, or if that may impact the currently running instances?

**Comment by Sineos** [comment]
When hitting Deploy node-red will (as far as my understanding to node-red's event systems goes) restart all the nodes.
```
		this.on("close", function() {
			if (tout) {
				clearTimeout(tout);
			}
			node.status({});
		});
```
The above code will be called and clears all running timeouts thus allowing a clean start of the newly deployed flow.

**Comment by kodarn** [comment]
Thank you very much for your explanation!

I will do my development on a separate instance of Node-Red then.
