### ISSUE TITLE
How is this different to existing trigger ?

### ISSUE THREAD

**Issue by dceejay** [Sineos/node-red-contrib-timeouttrigger#3]
Hi - If I have an existing trigger node set to send nothing and extend it's timeout before sending it's 2nd output, and wire it in parallel with an existing bypass wire ... how is this different ?

**Comment by Sineos** [comment]
Um, I don't quite get to what you are up to. Can you post a screenshot of the flow?

**Comment by dceejay** [comment]
![image](https://user-images.githubusercontent.com/5375409/37855009-254722a0-2ee5-11e8-98f5-513227972fd9.png)

As long as data keeps arriving within 5 seconds the trigger will not fire... 
as soon as it stops... 5 seconds later the "no more data" message will be sent.


```
[{"id":"7efc1ccf.4284c4","type":"inject","z":"3060d57c.1be71a","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":460,"wires":[["d22d7008.169d2","4e68ec28.fd0574"]]},{"id":"4e68ec28.fd0574","type":"debug","z":"3060d57c.1be71a","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":610,"y":460,"wires":[]},{"id":"d22d7008.169d2","type":"trigger","z":"3060d57c.1be71a","op1":"","op2":"no more data","op1type":"nul","op2type":"str","duration":"5","extend":true,"units":"s","reset":"","bytopic":"all","name":"","x":380,"y":540,"wires":[["4e68ec28.fd0574"]]}]
```

**Comment by Sineos** [comment]
Well, in fact it is no different to what you posted above. It just did not come to my mind to do it like this, so I coded this node.

Nice one 👍

**Comment by dceejay** [comment]
OK - no problem - just checking I wasn't missing anything :-)
