### ISSUE TITLE
No message pass through after reinstallation of the node

### ISSUE THREAD

**Issue by ol65** [Sineos/node-red-contrib-timeouttrigger#5]
After reinstalling this package in a working Node-Red flow, I need to touch all timeout nodes in all my flows and redeploy the flows

**Comment by Blaven1** [comment]
Same here - major problem - huge amunt of work to redo my flows with this problem. I need to re-deploy new nodes and re-wire the flows

**Comment by Sineos** [comment]
I tried to replicate this issue but did not succeed. Can you provide some directions how to provoke this?

**Comment by Blaven1** [comment]
Hi - thanks for the response. it happened on both occassions where i changed my pi OS to a newer version. Then I installed the newest Node red version. These were fresh installs on sd card (not upgrades). Through the node-red pallette, I imported the non-standard nodes - eg this timeout node.  I imported my flows, and everything works except the timeout node no longer passes through messages.
Dragging a new timeout node into the flow, dleting the exsiting one and re-wiring, fixes the problem - very weird.

thanks

**Comment by Sineos** [comment]
Sorry, but I cannot reproduce:

What I did:
1. Created this flow in one of my existing NR installation:
![grafik](https://github.com/Sineos/node-red-contrib-timeouttrigger/assets/4459312/2b64afee-8fb6-4dcd-b13e-bc900f9f7051)
2. Installed a complete new NR setup on a machine that has never seen one before
3. Used the palette to install timeouttrigger
4. Exported the flow from No. 1 
5. Imported the flow into the newly created Node-Red from No. 2
6. Deployed it

Result: The node starts working without any need for manual intervention.

I did No 1 twice: One time from an ages old NR v2.2 installation and one time from a pretty recent v3.1.3 installation. I followed the above procedure and in both cases it started as expected.

I'd really like to solve the issue, but without a way to reproduce, I can hardly do anything.

**Comment by Sineos** [comment]
Should be fixed now. 
With the kind help of @steve-mcl it was determined that the `passthorugh` variable was not correctly initialized on the server side when coming from an older version of the node.

**Comment by ol65** [comment]
Thank you! 😊

**Comment by Blaven1** [comment]
Brill - many thanks
