### ISSUE TITLE
Re-trigger option

### ISSUE THREAD

**Issue by bennybubble** [Sineos/node-red-contrib-timeouttrigger#7]
Hi,

Not an issue but feedback :  Please consider a re-trigger option: 

if the node times-out reset the timeouttrigger and wait another X time and generate another timeout.

-ben

**Comment by Sineos** [comment]
Not sure if this is a common case or rather an edge case. 
Probably you can quite easily work around this by doing something like:

```
[
    {
        "id": "ae11a883ba2f1562",
        "type": "inject",
        "z": "3d387a2215a48167",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 260,
        "y": 1100,
        "wires": [
            [
                "1383021fe30e7c28"
            ]
        ]
    },
    {
        "id": "1383021fe30e7c28",
        "type": "timeouttrigger",
        "z": "3d387a2215a48167",
        "ontimeouttype": "str",
        "ontimeoutval": "TO",
        "duration": "5",
        "units": "s",
        "passthrough": true,
        "name": "",
        "x": 430,
        "y": 1100,
        "wires": [
            [
                "0fe3d16cbdc09314",
                "36314bc8afd5c9fc"
            ]
        ]
    },
    {
        "id": "0fe3d16cbdc09314",
        "type": "switch",
        "z": "3d387a2215a48167",
        "name": "Only TimeOut Value",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "TO",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 600,
        "y": 1160,
        "wires": [
            [
                "791c7b9518b63c2c"
            ]
        ]
    },
    {
        "id": "36314bc8afd5c9fc",
        "type": "debug",
        "z": "3d387a2215a48167",
        "name": "debug 6",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 900,
        "y": 1100,
        "wires": []
    },
    {
        "id": "791c7b9518b63c2c",
        "type": "trigger",
        "z": "3d387a2215a48167",
        "name": "Retrigger",
        "op1": "",
        "op2": "TO2",
        "op1type": "nul",
        "op2type": "str",
        "duration": "3",
        "extend": false,
        "overrideDelay": false,
        "units": "s",
        "reset": "",
        "bytopic": "all",
        "topic": "topic",
        "outputs": 1,
        "x": 780,
        "y": 1160,
        "wires": [
            [
                "36314bc8afd5c9fc"
            ]
        ]
    }
]
```

**Comment by bennybubble** [comment]
Hi ,

I tried you solution but is doesn't work: if nothing comes in (so timeout) I want to sent a pre-fined payload over and over until the original signal ( ie timestamp) comes back again.

**Comment by Sineos** [comment]
Ah, OK. Now I get what you want. Indeed, this can also be done with standard nodes but is not so elegant.
Try the version in https://github.com/Sineos/node-red-contrib-timeouttrigger/tree/retrigger
Guess the easiest way is to download [timeouttrigger.html](https://github.com/Sineos/node-red-contrib-timeouttrigger/blob/retrigger/timeouttrigger.html) and [timeouttrigger.js](https://github.com/Sineos/node-red-contrib-timeouttrigger/blob/retrigger/timeouttrigger.js) and replace the ones in your installation.

Alternatively, run
`npm install "https://github.com/Sineos/node-red-contrib-timeouttrigger.git#retrigger" --save`
in your folder of Node Red (where the `node_modules` is).

I took the opportunity to modernize the code a bit.

@ol65, @blaven1 and @bartbutenaers, I'd appreciate your testing too. I'd hate to mess your flows because I goofed somewhere.

**Comment by bennybubble** [comment]
Hi, 

Works as requested with one minor remark:
After the initial 'Time-out' time it waits another 'Interval' time before sending the 'Send on Time-Out' value.
It would be nice if it sends the 'Send on Time-Out' value directly after the 'Time-out' and then repeats after the selected  'Interval' time.

Thanks!

**Comment by Sineos** [comment]
Makes sense. I updated the branch to reflect this.

**Comment by bennybubble** [comment]
Updated the code and works like a charm, many thanks for this extra feature!

**Comment by Sineos** [comment]
Excellent.

I'll leave it open for some days if there is additional feedback.
Then I'll push it to master and update npm.

**Comment by bennybubble** [comment]
Oeps, noticed one more thing:

If there is no data coming in (after deploying) the timeout won't start. I added an **Inject** node to get things starting but it would be nice if this functionality could be added in your node :-)

-ben

**Comment by Sineos** [comment]
> If there is no data coming in (after deploying) the timeout won't start.

This is a behavior that has been present since the beginning of this node. 
I'm hesitant to change this since this would be a breaking change and might affect the logic of existing flows. In the end, something that has never done anything cannot time out.

**Comment by bennybubble** [comment]
Makes sense!
